services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain-academy
    env_file:
      - .env
    # ports:
    #  - "56091:56091" # langgraph_sdk 用に開けたが、langgraph_sdkは動かなかった。
    #  - "8123:8123" # langgraph_sdk 用に開けたが、langgraph_sdkは動かなかった。
    #  - "8888:8888" # for jupyter
    volumes:
      - type: bind
        source: .
        target: /app
      # in order to use git in docker shell when using devcontainer
      - ~/.gitconfig:/root/.gitconfig:ro
      # additional setting for using git with remote repository
      #   - ~/.ssh:/root/.ssh:ro
      #   - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      # environment:
      #   - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    tty: true
    stdin_open: true
